name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Install InvokeBuild Module'
        shell: pwsh
        run: Install-Module -Name InvokeBuild -Force
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
      - name: 'Restore'
        shell: pwsh
        run: .\restore.ps1 -Instance ${{github.run_id}}
      - name: 'Format'
        shell: pwsh
        run: .\format.ps1 -Instance ${{github.run_id}}

      - name: Super-linter
        uses: super-linter/super-linter@v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
